name: "Publish To OSS"

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v2.4.0

      # step 2
      - name: "Setup Java JDK"
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: 8
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USER }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}

      # step 3
      - name: "Install GPG Secret Key"
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      # step 4
      - name: "Publish To OSS"
        run: mvn clean deploy --batch-mode -Dmaven.gpg.passphrase=${{ secrets.GPG_PASSPHRASE }} -e -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
